"""esquema inicial

Revision ID: adb21810f740
Revises: 
Create Date: 2026-09-17 14:43:03.558544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adb21810f740'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contraparte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=True),
    sa.Column('tipo', sa.Enum('proveedor', 'cliente', 'mandante', 'otro', name='contrapartetipo', native_enum=False, length=50), nullable=False),
    sa.Column('contacto_nombre', sa.String(length=150), nullable=True),
    sa.Column('contacto_email', sa.String(length=150), nullable=True),
    sa.Column('contacto_telefono', sa.String(length=50), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('formato_estandar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('vigente', sa.Boolean(), nullable=False),
    sa.Column('aprobado_por', sa.String(length=120), nullable=False),
    sa.Column('fecha_aprobacion', sa.Date(), nullable=False),
    sa.Column('campos_variables', sa.JSON(), nullable=False),
    sa.Column('ruta_plantilla', sa.String(length=255), nullable=False),
    sa.Column('checksum_base', sa.String(length=128), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', 'version', name='uq_formato_nombre_version')
    )
    op.create_table('garantia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=20), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('seriedad_oferta', 'fiel_cumplimiento', 'anticipo', 'correcta_ejecucion', 'otra', name='garantiatipo', native_enum=False, length=50), nullable=False),
    sa.Column('instrumento', sa.Enum('boleta_bancaria', 'poliza_seguro', 'retencion', 'pagare', 'otro', name='garantiainstrumento', native_enum=False, length=50), nullable=False),
    sa.Column('emisor', sa.String(length=120), nullable=True),
    sa.Column('numero', sa.String(length=60), nullable=True),
    sa.Column('monto', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('moneda', sa.Enum('CLP', 'UF', 'USD', 'EUR', 'otro', name='moneda', native_enum=False, length=50), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('vigente', 'por_vencer', 'vencida', 'ejecutada', 'devuelta', 'reemplazada', name='garantiaestado', native_enum=False, length=50), nullable=False),
    sa.Column('glosa', sa.Text(), nullable=True),
    sa.Column('documento_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_garantia_entidad', 'garantia', ['entidad_tipo', 'entidad_id'], unique=False)
    op.create_table('parametro',
    sa.Column('clave', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('unidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.Enum('solicitante', 'interna', name='unidadtipo', native_enum=False, length=50), nullable=False),
    sa.Column('jefatura_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('licitacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('codigo_externo', sa.String(length=60), nullable=True),
    sa.Column('objeto', sa.Text(), nullable=False),
    sa.Column('mandante', sa.String(length=200), nullable=True),
    sa.Column('contraparte_id', sa.Integer(), nullable=True),
    sa.Column('unidad_solicitante_id', sa.Integer(), nullable=False),
    sa.Column('fase', sa.Enum('pre_adjudicacion', 'formalizacion', 'cerrada', name='licitacionfase', native_enum=False, length=50), nullable=False),
    sa.Column('estado', sa.Enum('ingreso_antecedentes', 'examen_admisibilidad', 'revision_bases', 'preparacion_oferta', 'presentacion_oferta', 'evaluacion_resultado', 'adjudicada', 'no_adjudicada', 'desierta', 'desistida', 'descartado', name='estadolicitacion', native_enum=False, length=50), nullable=False),
    sa.Column('fecha_publicacion_bases', sa.Date(), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('fecha_cierre_ofertas', sa.Date(), nullable=True),
    sa.Column('fecha_apertura', sa.Date(), nullable=True),
    sa.Column('presupuesto_referencia', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('moneda', sa.Enum('CLP', 'UF', 'USD', 'EUR', 'otro', name='moneda', native_enum=False, length=50), nullable=True),
    sa.Column('exige_garantia_seriedad', sa.Boolean(), nullable=False),
    sa.Column('resultado', sa.Enum('en_proceso', 'adjudicado', 'no_adjudicado', 'desierto', 'desistido', name='licitacionresultado', native_enum=False, length=50), nullable=False),
    sa.Column('fecha_resultado', sa.Date(), nullable=True),
    sa.Column('contrato_id', sa.Integer(), nullable=True),
    sa.Column('informe_riesgos_id', sa.Integer(), nullable=True),
    sa.Column('analisis_interno', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contraparte_id'], ['contraparte.id'], ),
    sa.ForeignKeyConstraint(['unidad_solicitante_id'], ['unidad.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('rol', sa.Enum('unidad_solicitante', 'jefatura', 'legal', 'admin_licitaciones', 'financiera', 'tecnica', 'gerencia', 'admin_contratos', 'admin_sistema', name='rol', native_enum=False, length=50), nullable=False),
    sa.Column('unidad_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['unidad_id'], ['unidad.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('codigo_externo', sa.String(length=60), nullable=True),
    sa.Column('linea', sa.Enum('A_regular', 'B_autogestionado', 'C_licitacion', name='lineacontrato', native_enum=False, length=50), nullable=False),
    sa.Column('objeto', sa.Text(), nullable=False),
    sa.Column('categoria', sa.Enum('servicio', 'suministro', 'arriendo', 'obra', 'licencia', 'otro', name='categoriacontrato', native_enum=False, length=50), nullable=True),
    sa.Column('unidad_solicitante_id', sa.Integer(), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('contraparte_id', sa.Integer(), nullable=True),
    sa.Column('abogado_id', sa.Integer(), nullable=True),
    sa.Column('administrador_id', sa.Integer(), nullable=True),
    sa.Column('formato_id', sa.Integer(), nullable=True),
    sa.Column('licitacion_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('ingreso', 'aprobacion_jefatura', 'aprobacion_gerencia', 'admisibilidad_1', 'admisibilidad_2', 'elaboracion', 'visacion', 'firma', 'integracion', 'vigente', 'terminado', 'aclaraciones', 'descartado', 'formalizacion_ajuste', 'constitucion_garantias', name='estadocontrato', native_enum=False, length=50), nullable=False),
    sa.Column('estado_desde', sa.DateTime(), nullable=False),
    sa.Column('retorno_a', sa.String(length=50), nullable=True),
    sa.Column('requiere_aprobacion_gerencia', sa.Boolean(), nullable=False),
    sa.Column('requiere_garantia', sa.Boolean(), nullable=False),
    sa.Column('requiere_visacion_contraparte', sa.Boolean(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('moneda', sa.Enum('CLP', 'UF', 'USD', 'EUR', 'otro', name='moneda', native_enum=False, length=50), nullable=True),
    sa.Column('monto_referencia_clp', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('fecha_aprobacion_jefatura', sa.Date(), nullable=True),
    sa.Column('fecha_admisibilidad', sa.Date(), nullable=True),
    sa.Column('fecha_visacion', sa.Date(), nullable=True),
    sa.Column('fecha_firma', sa.Date(), nullable=True),
    sa.Column('fecha_integracion', sa.Date(), nullable=True),
    sa.Column('fecha_inicio_vigencia', sa.Date(), nullable=True),
    sa.Column('fecha_fin_vigencia', sa.Date(), nullable=True),
    sa.Column('vigencia_indefinida', sa.Boolean(), nullable=False),
    sa.Column('tipo_renovacion', sa.Enum('sin_renovacion', 'automatica', 'con_aviso', 'manual', name='tiporenovacion', native_enum=False, length=50), nullable=False),
    sa.Column('aviso_previo_dias', sa.Integer(), nullable=False),
    sa.Column('causales_termino', sa.Text(), nullable=True),
    sa.Column('motivo_descarte', sa.Text(), nullable=True),
    sa.Column('fecha_cierre', sa.Date(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['abogado_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['administrador_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['contraparte_id'], ['contraparte.id'], ),
    sa.ForeignKeyConstraint(['formato_id'], ['formato_estandar.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['unidad_solicitante_id'], ['unidad.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=20), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('solicitud', 'antecedente', 'borrador', 'contrato_firmado', 'anexo', 'garantia', 'bases', 'oferta_tecnica', 'oferta_economica', 'informe_riesgos', 'acta', 'otro', name='documentotipo', native_enum=False, length=50), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('ruta', sa.String(length=500), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=True),
    sa.Column('cargado_por_id', sa.Integer(), nullable=False),
    sa.Column('cargado_en', sa.DateTime(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cargado_por_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documento_entidad', 'documento', ['entidad_tipo', 'entidad_id'], unique=False)
    op.create_table('evento_estado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=20), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('estado_origen', sa.String(length=50), nullable=True),
    sa.Column('estado_destino', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_actor', sa.String(length=40), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('retorno_a', sa.String(length=50), nullable=True),
    sa.Column('documento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evento_entidad', 'evento_estado', ['entidad_tipo', 'entidad_id', 'fecha'], unique=False)
    op.create_table('hito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('inicio_ejecucion', 'entregable', 'pago', 'renovacion', 'termino', 'revision', 'otro', name='hitotipo', native_enum=False, length=50), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('fecha_planificada', sa.Date(), nullable=False),
    sa.Column('fecha_real', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'cumplido', 'atrasado', 'cancelado', name='hitoestado', native_enum=False, length=50), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('multa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('moneda', sa.Enum('CLP', 'UF', 'USD', 'EUR', 'otro', name='moneda', native_enum=False, length=50), nullable=False),
    sa.Column('fecha_aplicacion', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('propuesta', 'aplicada', 'en_disputa', 'pagada', 'condonada', name='multaestado', native_enum=False, length=50), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('multa')
    op.drop_table('hito')
    op.drop_index('ix_evento_entidad', table_name='evento_estado')
    op.drop_table('evento_estado')
    op.drop_index('ix_documento_entidad', table_name='documento')
    op.drop_table('documento')
    op.drop_table('contrato')
    op.drop_table('usuario')
    op.drop_table('licitacion')
    op.drop_table('unidad')
    op.drop_table('parametro')
    op.drop_index('ix_garantia_entidad', table_name='garantia')
    op.drop_table('garantia')
    op.drop_table('formato_estandar')
    op.drop_table('contraparte')
    # ### end Alembic commands ###
